### ISSUE TITLE
[Bug]: ListenBrainzClient.ToListens() returns an incorrect timestamp if the same song is stored multiple times

### ISSUE THREAD

**Issue by Maxr1998** [lyarenei/jellyfin-plugin-listenbrainz#112]
### Bug description

I recently noticed that some listens I manually inserted into the cache\* were silently dropped during submission. Through some debugging, I found that the ListenBrainzClient.ToListens() returns the same timestamp for all listens of the same song stored in the cache, thus being counted as duplicates on the ListenBrainz server and silently dropped.

\* This is because I listened to these songs on another (mobile) player, but the same should apply when simply using Jellyfin on the local network while internet is down/ListenBrainz is unreachable.

### Steps to reproduce / Actual behavior

Listen to a specific song multiple times while being unable to connect to ListenBrainz, thus forcing them to be stored in the offline cache. It doesn't matter if or how many songs are listened in between.
When the connection has been restored and the resubmit listens task is executed, the [`ListenBrainzClient.ToListens()`](https://github.com/lyarenei/jellyfin-plugin-listenbrainz/blob/72d1898318e2cb74177d29e66374d3c8852e5bbd/src/Jellyfin.Plugin.ListenBrainz/Clients/ListenBrainzClient.cs#L240) uses the first `ListenedAt` for a song, thus re-using the same for all instances of listening to that specific song.

Thus, these listens are silently dropped by the server during submission due to sharing the same timestamp.

### Expected behavior

Multiple listens of the same song should be correctly submitted, even when the offline cache is used.

### Jellyfin logs

Not applicable.

### Plugin version

5.0.1.0

### Jellyfin Version

10.10.0

**Comment by Maxr1998** [comment]
I suggest this patch to resolve the issue, please let me know if you want me to open a PR.

```diff
         if (_libraryManager is null) throw new InvalidOperationException("Library manager is not available");
 
         var listensToConvert = storedListens.ToArray();
-        return listensToConvert
-            .Select(l => _libraryManager.GetItemById(l.Id))
-            .Cast<Audio>()
-            .Select(a => a.AsListen(
-                listensToConvert.First(l => l.Id == a.Id).ListenedAt,
-                listensToConvert.First(l => l.Id == a.Id).Metadata));
+        return listensToConvert.Select(l =>
+        {
+            var baseItem = _libraryManager.GetItemById(l.Id);
+            var audio = (Audio?)baseItem ?? throw new PluginException("Invalid item");
+            return audio.AsListen(l.ListenedAt, l.Metadata);
+        });
     }
 
     /// <summary>
```

**Comment by lyarenei** [comment]
@Maxr1998 Thanks for reporting. Yeah, now I see.. What a dumb mistake... 😅

Anyway, I don't mind you opening a pull request. It's even better - as the code will be properly attributed and I would not need to put comments with links, etc... 🙂

**Comment by Maxr1998** [comment]
Alright, will do then!
