### ISSUE TITLE
New feature: Option to select which libraries to enable listen submission

### ISSUE THREAD

**Issue by yoooogaQAQ** [lyarenei/jellyfin-plugin-listenbrainz#39]
Currently this plugin submit audio listens in all libraries.

It would be nice to have the option that allows users to select specific libraries to enable listen submission.

For example, some users may prefer:
- Not to submit audiobook listens in a Books library
- Only submit listens in specific libraries

**Comment by lyarenei** [comment]
Sounds good. I'll take a look into it.

**Comment by lyarenei** [comment]
Hi @kyrinyoga, I believe it should be pretty much done. 
If you want, you can try plugin version `3.1.0.0`. To get it, you can either install it manually (plugin build available [here](https://github.com/lyarenei/jellyfin-plugin-listenbrainz/actions/runs/5777452382)), or add my development repo `https://repo.xkrivo.net/jellyfin-dev/manifest.json` to your server and install it from there.

The implemented behavior is described in the [documentation](https://github.com/lyarenei/jellyfin-plugin-listenbrainz/blob/exclude-libraries/doc/configuration.md#allowed-libraries-for-listen-submission).

Also, in case you will go with the repo route, don't forget to remove it afterward, so you won't accidentally get upgrades to future (and potentially broken) development builds.

Let me know how it goes, thanks.
