### ISSUE TITLE
Favorite's not Syncing on Jellyfin 8.12

### ISSUE THREAD

**Issue by tuxfoo** [lyarenei/jellyfin-plugin-listenbrainz#58]
Selecting favorite in Jellyfin does not seem to work on 8.12 (I have not tried this plugin on earlier versions).

I tried selecting favorite on current playing song and one that was not playing and then playing it.

I also could not remove favorite/love from within Jellyfin. 

I have syncing for favorites enabled and alternative mode disabled.

**Comment by tuxfoo** [comment]
I wait for the track to finish playing, I enabled logging for "Jellyfin.Plugin.ListenBrainz"

As you mentioned it seems to be related to MSID/MBID.

Is the MSID fetched from musicbrainz?

```
[2023-12-04 00:25:09.971 +13:00] [INF] [57] Jellyfin.Plugin.ListenBrainz: No additional metadata available for track "I'm A Man You Don't Meet Every Day": "One or more errors occurred. (Audio item does not have a track MBID)"
[2023-12-04 00:25:09.971 +13:00] [DBG] [57] Jellyfin.Plugin.ListenBrainz: No additional metadata available
System.AggregateException: One or more errors occurred. (Audio item does not have a track MBID)
 ---> System.ArgumentException: Audio item does not have a track MBID
   at Jellyfin.Plugin.ListenBrainz.Clients.MusicBrainzClient.GetAudioItemMetadata(Audio item)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Jellyfin.Plugin.ListenBrainz.PluginImplementation.GetAdditionalMetadata(EventData data)
2023-12-04 00:25:09.971 +13:00] [DBG] [57] Jellyfin.Plugin.ListenBrainz: Sending request ("d1350f3"):
Method: "POST"
URI: https://api.listenbrainz.org/1/submit-listens
Data: "{\"listen_type\":\"single\",\"payload\":[{\"listened_at\":1701602709,\"track_metadata\":{\"artist_name\":\"The Pogues\",\"track_name\":\"I'm A Man You Don't Meet Every Day\",\"release_name\":\"Rum, Sodomy & The Lash\",\"additional_info\":{\"track_number\":4,\"tags\":[],\"media_player\":\"Jellyfin\",\"submission_client\":\"ListenBrainz plugin for Jellyfin\",\"submission_client_version\":\"3.1.2.0\",\"duration_ms\":175000}}}]}"
[2023-12-04 00:25:09.972 +13:00] [INF] [57] Jellyfin.Plugin.ListenBrainz: Favorite sync for track "I'm A Man You Don't Meet Every Day" and user "tuxfoo" failed: "Fallback to send feedback using MSID is not implemented"
[2023-12-04 00:25:09.972 +13:00] [DBG] [57] Jellyfin.Plugin.ListenBrainz: Favorite sync failed
Jellyfin.Plugin.ListenBrainz.Exceptions.MetadataException: Fallback to send feedback using MSID is not implemented
   at Jellyfin.Plugin.ListenBrainz.PluginImplementation.SendFeedbackUsingMsid()
   at Jellyfin.Plugin.ListenBrainz.PluginImplementation.HandleFavoriteSync(EventData data, AudioItemMetadata metadata, UserConfig userConfig)
```

**Comment by lyarenei** [comment]
Ah, I undestand now.

> It seems to be failing to pick up the MSID from musicbrainz.

No, MSIDs come from ListenBrainz, not MusicBrainz. However, I totally forgot to reimplement the fallback to the MSID - I just implemented the MBID part of the feedback API when rewriting the plugin and so the requests are failing, because there is no track MBID available in your case. This can be seen in the logs:

`[2023-12-04 00:25:09.972 +13:00] [INF] [57] Jellyfin.Plugin.ListenBrainz: Favorite sync for ... failed: "Fallback to send feedback using MSID is not implemented"`

> All my Albums have a "MusicBrainz Release Group Id" and "MusicBrainz Album Id" but none of the tracks seems to have any of the "External IDs"; this seems odd to me. Are these meant to be updated by the musicbrainz plugin when the the album is identified and metadata updated?

Actually, I have no idea. I tag all my music with Picard, so the metadata are directly saved to the files. Then Jellyfin just has to read them and pull additional metadata using the IDs and show them in the UI.

Looking briefly at the MusicBrainz plugin source, it looks like it has implemented providers for albums and artists. Not for tracks though. It only exposes them to the user, so you can view and edit them in the UI.

**Comment by tuxfoo** [comment]
> No, MSIDs come from ListenBrainz, not MusicBrainz. However, I totally forgot to reimplement the fallback to the MSID - I just implemented the MBID part of the feedback API when rewriting the plugin and so the requests are failing, because there is no track MBID available in your case. This can be seen in the logs:

Thanks for clarifying.

> > All my Albums have a "MusicBrainz Release Group Id" and "MusicBrainz Album Id" but none of the tracks seems to have any of the "External IDs"; this seems odd to me. Are these meant to be updated by the musicbrainz plugin when the the album is identified and metadata updated?
> 
> Actually, I have no idea. I tag all my music with Picard, so the metadata are directly saved to the files. Then Jellyfin just has to read them and pull additional metadata using the IDs and show them in the UI.
> 
> Looking briefly at the MusicBrainz plugin source, it looks like it has implemented providers for albums and artists. Not for tracks though. It only exposes them to the user, so you can view and edit them in the UI.

That was my observation from looking at the settings, I rather avoid making changes to the original files, I might look for a way of adding these to the Jellyfin database or make a CR for the musicbrainz plugin to add this feature.

**Comment by tuxfoo** [comment]
As a work around I created a python script to get the MBID for every track add it to Jellyfin since Jellyfin does add the MBID for the albums. If I knew C# I would have just fixed Jellyfin.Plugin.MetaBrainz.Plugin and made PR.

It managed to tag about 75% of my tracks (There was issues with some types of multi disc albums).
