### ISSUE TITLE
[Request]: Include ISRCs in submission when available

### ISSUE THREAD

**Issue by UnviableFriend** [lyarenei/jellyfin-plugin-listenbrainz#66]
### Description

If you inspect listens submitted from spotify on ListenBrainz you will see ISRCs are included in the additional_info of each submission. Picard (And possibly others?) will embed ISRCs in files when they are available on MusicBrainz. It would be great if the plugin would submit the ISRCs as well if they are available in the file.
Currently ISRCs aren't used by ListenBrainz to help matches, but that could change one day. And more data is always better!

**Comment by lyarenei** [comment]
Thanks for the suggestion. I looked into the code and saw that the field is there, so it looks like I just didn't implement getting the ISRC from MusicBrainz for some reason.

Please try plugin version `3.3.0.0`, which should be available shortly. Let me know if there are any issues.
