### ISSUE TITLE
Retry submitting listens on server error

### ISSUE THREAD

**Issue by Maxr1998** [lyarenei/jellyfin-plugin-listenbrainz#7]
I've noticed ListenBrainz throws a "Bad Gateway" server error from time to time:

```
[DBG] [39] Jellyfin.Plugin.Listenbrainz.ServerEntryPoint: Raw response: {"code":503,"error":"Cannot submit listens to queue, please try again later."}
```

In that case, the plugin should retry submitting that listen, preferably with exponential backoff.
Alternatively, it could print the whole listen data to the console as JSON so that you could manually re-submit the listen at a later date.

**Comment by lyarenei** [comment]
Hi, thanks for reporting.

> the plugin should retry submitting that listen, preferably with exponential backoff.

I agree, I'll look into that when I have some free time.

> Alternatively, it could print the whole listen data to the console as JSON so that you could manually re-submit the listen at a later date.

Personally, I think it would be best to implement some sort of cache and have a scheduled job to retry submitting these. However, I'm not sure if this is something a Jellyfin plugin can do self-contained (i.e. work with sqlite db/external files). But even if this would be possible, I'd like to clean up the source code first as it's a mess and I've been working with c# for some time now and gained some experience.

Anyway, the raw request printing looks like a good stopgap solution (and maybe it would be also useful in debugging). So I'll implement that one as well.

**Comment by Maxr1998** [comment]
Awesome, thanks for the response and planning to look into it!

**Comment by lyarenei** [comment]
Implemented retries and improved logging in plugin ver:
- 1.2.1.0 => JF 10.7.x
- 2.0.0.1 => JF 10.8.x

The repository in JF UI should report these new versions, so you should be able to easily upgrade the plugin.

Note that I left the old logging there, so there will be some redundant/useless logs - these will be probably removed in the big code cleanup mentioned earlier.

I'll be closing this issue for now. Feel free to reopen if you notice any relevant issues.

**Comment by Maxr1998** [comment]
Awesome, thanks a lot for adding this!
Will upgrade momentarily and report back in case I notice any issues.
