### ISSUE TITLE
[Bug]: track number field doesn't match docs

### ISSUE THREAD

**Issue by UnviableFriend** [lyarenei/jellyfin-plugin-listenbrainz#71]
### Bug description

I was comparing data all the different LB submission clients sent and noticed an inconsistency, and checking the docs it seems the format for the track number field by this plugin is slightly incorrect.
https://listenbrainz.readthedocs.io/en/latest/users/json.html#payload-json-details
The Jellyfin Plugin is sending
`track_metadata.additional_info.track_number` where most other clients, and the docs use `track_metadata.additional_info.tracknumber`
Relatively minor but thought I would mention it as it would be a small change.

### Steps to reproduce

Click 3 dot menu on LB listens page, inspect listen

### Plugin version

3.3.0.0

### Jellyfin Version

10.8.13

**Comment by lyarenei** [comment]
@UnviableFriend Nice find, thanks for reporting. It should be fixed with plugin version `3.3.1.0`.
